### PR TITLE
Change 1 line for compatibility with versions with fixed and non-fixe…

### PR DESCRIPTION
**Pull request by jadepoirier**
…d variance, add docstring and plt.show() in plot_fit srp_extrafuncs

### CODE REVIEW

**Review by jgbeninger — CHANGES_REQUESTED** [review]
Line should be "mean, efficacies" not just mean. The easySRP.runISISvec method returns a tuple of form (mean, efficacies) not just the mean. I will update the method docstring.

**Comment by jadepoirier** [comment]
I am selecting index 0, so it is selecting the mean. I changed it this way so that if the user is using it with non-fixed variance, it will still work (i.e., with fixed variance it returns (mean, efficacies), with non-fixed it returns (mean, sigma, efficacies); either way mean has index 0). I am using it in the protocol to plot with the fit_srp_gridsearch version.

**Comment by jgbeninger** [comment]
If the structure is not just the mean (i.e. a float) it shouldn't be labeled "mean". Also, line 297 read: "axis.plot(xax, mean, color="#cc3311", label="SRP model")" which suggests that mean is being used directly as a vector of mean values, not with a selected index? Finally, the docstring specifies that the model input should be of type easySRP so the user presumably shouldn't be submitting a different model. Adding a check for this or changing the function name to be more specific would be better. Otherwise there is a risk of users passing in one type of model and getting results they think are from a different type.

**Comment by jgbeninger** [comment]
I am confused, why are you using this with fit_srp_model_gridsearch if the model type is easySRP? That function explicitly trains an ExpSRP model. The "mean" _parameter_ in that model is used with the sigma to infer the "shape" and "scale" of a gamma distribution fit via maximum likelihood estimation.

**Comment by jadepoirier** [comment]
The mean is the mean (not a tuple) from the start: mean = model.run_ISIvec(stimulus_dict[name_protocol])**[0]**. Set this way, plot_fit would be able to plot the mean fit of any model (since run_ISIvec always returns mean with index 0). I thought this would save me the trouble of having to figure out beforehand what model they are using, or creating functions for each models. And I am using ExpSRP with fit_srp_gridsearch, that is why model.run_ISIvec returns mean, sigma, efficacies

**Comment by jgbeninger** [comment]
See comment above, these parameters have different mathematical meanings when compared between the two models. They aren't interchangeable in this way. The mean prediction of ExpSRP comes from sampling the gamma distribution. That distribution is dependent on both the shape **and** the scale.

**Comment by jadepoirier** [comment]
Ok, I can see it isn't the mean fit, but it is still the fit (so plot_fit still makes sense). I could change the docstring to say that it also works with ExpSRP generally. I could add a note to the protocol and the code notebook to explain the difference between the "mean" of both, but I can't see why a user shouldn't use this plot function to visualize the fit when using ExpSRP

**Comment by jgbeninger** [comment]
It is not the fit.

**Pull request closed without merging**
